application: build-status-hrd
version: 11
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /imgs
  static_dir: imgs

- url: /favicon.ico
  static_files: imgs/favicon.ico
  upload: imgs/favicon.ico

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /.*
  script: build-status.app

